### ISSUE TITLE
mqtt 5.1.x requires node 18 (or newer)

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.mqtt-client#247]
When updating dependencies of mqtt to 5.x.x do not forget to raise engines to >= 18 as mqtt 5.1.0 requires node 18 or newer

see https://t.me/ioBroker_development/31757

**Comment by Apollon77** [comment]
There will be an update of the lib,. so a dep increase should fix this again

**Comment by mcm1957** [comment]
ok, so then this isssue seems to be obsolete
