### ISSUE TITLE
Minor Security Improvement: Make Use of "protectedNative" and "encryptedNative" for Sensitive Data

### ISSUE THREAD

**Issue by stevenengland** [iobroker-community-adapters/ioBroker.mqtt-client#319]
Hi there,

I recognized that the native key called
`password`
in the io-package.json file that has no counterpart in
`encryptedNative`
`protectedNative`
Thus the value will be stored in plain text and accessable by other adapters. See https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#adapter for more information for those two arrays.

Maybe in of the next releases you could bring this imrovement in.
Hint: Adjusting these values would mean to release another major version of the adapter.

**Comment by mcm1957** [comment]
@Apollon77:
This adapter stil uses index_m.html.
Is it possible to use encryptedNative/protectedNative ?

**Comment by Apollon77** [comment]
Sure. But would be breaking in any case . And in factcheck is also an open issue with pin vs password. Seems pin should be optional.

**Comment by klein0r** [comment]
Added in 2.0.0 (with upgrade warning to re-enter the password)
